[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  framework = "#static"